### ISSUE TITLE
On boot, VM tries to start before virtualbox.service is up

### ISSUE THREAD

**Issue by brettw-splunk** [pragmaticlinuxblog/systemdstartvboxvm#2]
Added virtualbox.service to _After=_ and this fixed it for me. Great blog post by the way!

**Comment by pragmaticlinuxblog** [comment]
Thank you for the feedback. I assumed vboxdrv.service would be enough for the After= statement. I'll keep an eye on it, to see if others have the same issue. If so, I'll update it to wait for virtualbox.service as well.
